### ISSUE TITLE
use-motion-binding doesn't update binding onComplete

### ISSUE THREAD

**Issue by chess123mate** [howmanysmall/react-ripple#2]
This is problematic for calls to `immediate`. It can be fixed by adding `currentMotion.onComplete(setBinding)` right after the `currentMotion.onStep(setBinding)` call. (Browsing through the code, onStep looks like it's supposed to be getting called when the motion *wasn't* complete? But adding the `onComplete` line fixed the problem I was experiencing.)

**Comment by howmanysmall** [comment]
actually insane bro thanks again, fixed in 2.0.3
